<?php

namespace OC\PlatformeBundle\Repository;

/**
 * IncidentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentsRepository extends \Doctrine\ORM\EntityRepository
{
}
